# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statId', models.PositiveIntegerField(default=0)),
                ('statNm', models.CharField(max_length=100)),
                ('chgerId', models.PositiveIntegerField(default=0)),
                ('chgerType', models.PositiveIntegerField(default=0)),
                ('stat', models.PositiveIntegerField(default=0)),
                ('addrDoro', models.CharField(max_length=100)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('useTime', models.CharField(max_length=100)),
                ('LastUsedTime', models.CharField(max_length=20)),
            ],
        ),
    ]
