# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('title', models.TextField()),
                ('writer', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
    ]
